[package]
name = "resvg-skia"
version = "0.1.0"
authors = ["JaFenix <51161647+JaFenix@users.noreply.github.com>"]
edition = "2018"
workspace = ".."

[dependencies]

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"
